--CREATE 쿼리문
CREATE TABLE EMP (
NO NUMBER, 
NAME VARCHAR2(20),
AGE NUMBER
);

CREATE TABLE CUSTOMER(
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    ADDRESS VARCHAR2(100)
);

CREATE TABLE ORDERS(
    ORDER_ID  NUMBER PRIMARY KEY,
    SALESMAN_ID NUMBER,
    ORDER_DATE DATE NOT NULL
);

CREATE TABLE CATEGORIES(
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(100) NOT NULL
);

CREATE TABLE LOCATION(
    LOCATION_ID NUMBER PRIMARY KEY,
    ADDRESS VARCHAR2(255) NOT NULL,
    POSTAL_CODE VARCHAR2(20),
    CITY VARCHAR2(50)
);

--INSERT INTO 데이터 삽입
INSERT INTO CUSTOMER(ID, NAME, ADDRESS) VALUES(1,'둘리','인천');      --일부 컬럼만 사용할 경우
INSERT INTO CUSTOMER(ID, NAME) values(3,'또치');
INSERT INTO CUSTOMER VALUES(2,'둘리','인천');       --전체 컬럼을 사용할 경우
INSERT INTO CUSTOMER VALUES(5, '둘리', '');       --공백을 넣어도 NULL로 들어감
--Insert Into CUSTOMER VALUES(7, '홍길동홍길동', NULL);
--INSERT INTO CUSTOMER VALUES(6, '홍길동', 'NULL');
--INSERT INTO CUSTOMER(ID, NAME) VALUES(3, '홍길동');    --ID는 PK키 이므로 중복되는 값이 올 수 없다.
--INSERT INTO CUSTOMER(ID, NAME, ADDRESS) VALUES(4, '둘리', '서울');
--INSERT INTO CUSTOMER(ID, ADDRESS) VALUES(5,'서울');   --Nullable이 No인 경우엔 반드시 데이터를 넣어줘야 한다.

--select * from nls_database_parameters where parameter = 'NLS_CHARACTERSET';

CREATE TABLE EMP2(
    EMPNO NUMBER(5) NOT NULL,   --5자리 정수
    NUM1 NUMBER(5),
    NUM2 NUMBER(5,2),    --5자리 숫자(정수 3자리 + 소수 2자리{소수점 3번째 자리에서 반올림})
    NUM3 NUMBER(6,-2)   --5자리 숫자(정수 3자리 + 소수점 왼쪽 첫째자리에서 반올림)
);

INSERT INTO EMP2 VALUES(12345, 1234, 123.123, 2874.15);

-- ALTER 문
ALTER TABLE CUSTOMER ADD GENDER VARCHAR2(9);    --컬럼 추가

ALTER TABLE CUSTOMER RENAME COLUMN GENDER TO GEN;   --컬럼 이름 바꾸기
ALTER TABLE CUSTOMER RENAME COLUMN GEN TO GENDER;

ALTER TABLE CUSTOMER MODIFY GENDER VARCHAR(100);    --컬럼 용량 바꾸기
